import { Roboto } from "next/font/google";
import "../styles/globals.css";
import Navbar from "@/components/navbar";
import FooterPage from "@/components/footer";
import { ToastContainer } from "react-toastify";
const inter = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "Tạp hóa MMO",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="bg-[#f8f8f8]">{children}</div>
        <FooterPage />
        <ToastContainer />
      </body>
    </html>
  );
}
