@baseUrl = http://localhost:8080/api


### Register a new user
GET {{baseUrl}}/categories/postShares
Content-Type: application/json

### Register a new user
GET {{baseUrl}}/categories/postShares/facebook
Content-Type: application/json


### Register a new user
GET {{baseUrl}}/categories/services
Content-Type: application/json

### Register a new user
GET {{baseUrl}}/categories/products
Content-Type: application/json


### Register a new user
GET {{baseUrl}}/categories/services/email
Content-Type: application/json






