@baseUrl = http://localhost:8080/api

GET {{baseUrl}}/services/dich-vu-twttier-x-buff-follow-sieu-re
Content-Type: application/json

###
GET {{baseUrl}}/services
Content-Type: application/json

### Login user
POST {{baseUrl}}/user/login
Content-Type: application/json

{
  "email":"trungpyy@gmail.com",
  "username": "trungpspy1",
  "password": "Trungpy78@",
  "role": "user"
}
### get all post
GET {{baseUrl}}/services/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMxYjNmZjZjLWQ2N2EtNGQ4OC1hYTI5LTA3NTM5YTJjZTQ0ZiIsInJvbGUiOiJDVVNUT01FUiIsImlhdCI6MTcyMTI5MDc4MywiZXhwIjoxNzIxNDYzNTgzfQ.-4xqfE6jdEOde_si_WLCEyaFdHZuSaZ6-w1QTxcTfa4

### get all post
GET {{baseUrl}}/services/fetch/service
Content-Type: application/json

### get all post
POST {{baseUrl}}/services/createReview/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMxYjNmZjZjLWQ2N2EtNGQ4OC1hYTI5LTA3NTM5YTJjZTQ0ZiIsInJvbGUiOiJDVVNUT01FUiIsImlhdCI6MTcyMTI5MDc4MywiZXhwIjoxNzIxNDYzNTgzfQ.-4xqfE6jdEOde_si_WLCEyaFdHZuSaZ6-w1QTxcTfa4

{
  "level":2,
  "content": "sản phẩm vip"
}